export const ROUTE_API_PARAMS: Record<string, string> = {
  'A-03': 'OCMzM2E5MmJjNmI0ZDA0YjA4LDEsNywxLDIxLjEyMTEyLC0xMDEuNzMwNTEsMTAsMjEuMTMxMjksLTEwMS43MTcwNQ==',
  'A-75': 'OCMzM2E5MmJjNmI0ZDA0YjA4LDEsNywyLDIxLjEyMzkzLC0xMDEuNzMwMzYsMTI3LDIxLjEzNTA0LC0xMDEuNzE3ODQ=',
  'A-31': 'OCMzM2E5MmJjNmI0ZDA0YjA4LDEsMSwyLDIxLjE0OTQ0LC0xMDEuNzMzODMsNTUsMjEuMTMyMzUsLTEwMS43MTU5Ng==',
  'L-03': 'OCMzM2E5MmJjNmI0ZDA0YjA4LDEsMSwyLDIxLjEzMjQsLTEwMS43MTYxMiw0ODEsMjEuMTQ0MjEsLTEwMS42ODU2OA==',
  'L-04': 'OCMzM2E5MmJjNmI0ZDA0YjA4LDEsMSwxLDIxLjEzMjQsLTEwMS43MTYxMiw0ODQsMjEuMDk1NTEsLTEwMS42MTgxOA==',
  'X-04': 'OCMzM2E5MmJjNmI0ZDA0YjA4LDEsNywyLDIxLjE0MDcxLC0xMDEuNjgzLDI4OSwyMS4wOTU0MiwtMTAxLjYxODQ',
}

export const VALID_ROUTE_IDS = Object.keys(ROUTE_API_PARAMS)
