export const ROUTE_API_PARAMS: Record<string, string> = {
  'A-03': 'OCMzM2E5MmJjNmI0ZDA0YjA4LDEsNywxLDIxLjEyMTEyLC0xMDEuNzMwNTEsMTAsMjEuMTMxMjksLTEwMS43MTcwNQ==',
  'A-75': 'OCMzM2E5MmJjNmI0ZDA0YjA4LDEsNywyLDIxLjEyMzkzLC0xMDEuNzMwMzYsMTI3LDIxLjEzNTA0LC0xMDEuNzE3ODQ=',
}

export const VALID_ROUTE_IDS = Object.keys(ROUTE_API_PARAMS)
